server:
  port: 8762
eureka:
  client:
    # 是否要注册到其他Eureka Server实例
    registerWithEureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/