server:
  port: 8765
spring:
  application:
    # 指定服务名称
    name: service-provider-lsc
  datasource:
        url: jdbc:mysql://localhsot:3306/spring-cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
        username: root
        password: bruce1008
        filters: log4j,wall,mergeStat
eureka:
  client:
    serviceUrl:
      # 指定eureka server地址
      defaultZone: http://localhost:8762/eureka/
  instance:
    # 指定是否注册IP到eureka server
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath*:com/lsc/dao/mapping/*.xml
  typeAliasesPackage: com.lsc.model.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性